spring.application.name=member-management

spring.datasource.url=jdbc:postgresql://localhost:5432/member
spring.datasource.username=postgres
spring.datasource.password=01012020

spring.jpa.hibernate.ddl-auto=update

app.jwt-expiration-milliseconds=3600000
app.jwt-secret=MySuperSecretKey123456789012345strongenough